# docker para subir bando de dados em ambiente isolado

version: '3'

services:
  api-pre-moldado-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apipremoldado
